CREATE TABLE IF NOT EXISTS mealfit.ingredient_price_mapping (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL REFERENCES mealfit.ingredient(ingredient_id),
    series_id BIGINT NOT NULL REFERENCES mealfit.price_series(series_id),
    mapping_type VARCHAR(20) NOT NULL,
    conversion_factor NUMERIC(12, 6) NOT NULL DEFAULT 1,
    confidence_score NUMERIC(5, 4) NOT NULL DEFAULT 1,
    priority INTEGER NOT NULL DEFAULT 100,
    review_status VARCHAR(20) NOT NULL DEFAULT 'PROPOSED',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ingredient_price_mapping UNIQUE (ingredient_id, series_id),
    CONSTRAINT ck_ingredient_price_mapping_type
        CHECK (mapping_type IN ('EXACT', 'VARIETY', 'RAW_PROXY', 'CATEGORY_PROXY')),
    CONSTRAINT ck_ingredient_price_mapping_review
        CHECK (review_status IN ('PROPOSED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_ingredient_price_mapping_factor CHECK (conversion_factor > 0),
    CONSTRAINT ck_ingredient_price_mapping_confidence
        CHECK (confidence_score >= 0 AND confidence_score <= 1)
);

CREATE INDEX IF NOT EXISTS ix_ingredient_price_mapping_lookup
    ON mealfit.ingredient_price_mapping
       (ingredient_id, review_status, is_active, priority);

CREATE INDEX IF NOT EXISTS ix_ingredient_price_mapping_series
    ON mealfit.ingredient_price_mapping(series_id);

-- 현재 price_series의 대표 식재료 연결은 정확한 승인 매핑으로 이관한다.
INSERT INTO mealfit.ingredient_price_mapping
    (ingredient_id, series_id, mapping_type, conversion_factor,
     confidence_score, priority, review_status, is_active)
SELECT ps.ingredient_id, ps.series_id, 'EXACT', 1, 1, 0, 'APPROVED', TRUE
FROM mealfit.price_series ps
ON CONFLICT (ingredient_id, series_id) DO UPDATE SET
    mapping_type = 'EXACT',
    conversion_factor = 1,
    confidence_score = 1,
    priority = 0,
    review_status = 'APPROVED',
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;

