CREATE TABLE IF NOT EXISTS mealfit.monthly_budget (
    budget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    budget_month DATE NOT NULL,
    budget_amount NUMERIC(15, 2) NOT NULL,
    executed_amount NUMERIC(15, 2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mealfit.meal_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    plan_date DATE NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    meal_count INTEGER NOT NULL,
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS mealfit.meal_plan_item (
    plan_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    slot_type VARCHAR(20) NOT NULL,
    menu_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS mealfit.menu (
    menu_id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);